typography_spectrum: 0.5533074481076202
content_rating:
  adult: false
color:
  brandStrength: 0.9205115676754256
  lightness: 0.8469753865775937
  saturation: 0.05103471227368285
  rhythmicContrast: 0.8236715490416171
  brandColors:
    - '#FFFFFF'
    - '#31BBAC'
    - '#D73226'
    - '#414242'
    - '#A6A8AB'
github: true
layout_spectrum: 0.8520606122440705
analytics:
  twitter: ''
  google: UA-93195675-1
  facebook: '381066988943490'
author:
  name: Henrique Utsch
  email: henriqueutsch@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/fa9c307a-4a74-4327-8bde-4c4135c28cd5.png
name: Full Life Academy
url: 'http://fulllifeacademy.com.br/'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: Blog
    url: 'http://blog.fulllifeacademy.com.br'
    type: external
  - name: Sobre o Fundador
    url: 'http://henriqueutsch.com.br'
    type: external
  - name: Facebook
    url: 'https://www.facebook.com/FullLifeAcademyCourse/'
    type: external
  - name: YouTube
    url: 'https://www.youtube.com/channel/UC9SaqyNSlScKfchf8FEH4SA'
    type: external
  - name: Linkedin
    url: 'https://www.linkedin.com/company-beta/16211769'
    type: external
  - name: Twitter
    url: 'https://twitter.com/fulllifeacademy'
    type: external
  - name: Instagram
    url: 'https://www.instagram.com/fulllifeacademy/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/99ee198f-247b-45a6-8fb5-020262d87978.png
title: Full Life Academy
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2Fu4_upeyFF7U%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Du4_upeyFF7U&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2Fu4_upeyFF7U%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      datePublished: null
      isBasedOnUrl: 'https://www.youtube.com/watch?v=u4_upeyFF7U'
      keywords:
        - duration
        - ilhabela
        - views
        - sol
        - henrique
        - utsch
        - ilha
        - duas
        - passagens
        - rter
      related: []
      author:
        - name: Henrique Utsch
          url: 'https://www.youtube.com/user/henriquetutsch'
          avatar: {}
      '@context': 'http://schema.org'
      title: Por do sol Ilhabela
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=u4_upeyFF7U&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=u4_upeyFF7U&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=u4_upeyFF7U&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=u4_upeyFF7U&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=u4_upeyFF7U&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=u4_upeyFF7U'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=u4_upeyFF7U
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=u4_upeyFF7U
          package: '544007664'
          namespace: google
          type: ios
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
        domain: www.youtube.com
      description: Uploaded by Henrique Utsch on 2016-05-10.
      inLanguage: en
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: >-
  Nossa proposta é reunir ferramentas para impulsionar o ser humano a outro
  patamar, muito mais elevado e completo. Reunindo as áreas mais procuradas com
  o propósito de uma vida mais feliz e plena onde todos os cursos se conectam
  preparando o ser humano para a nova era da humanidade. Uma era com humanos
  mais conscientes e bem preparados para uma vida com propósito, tecnologia e
  espiritualidade. Desenvolva todas as suas capacidades como ser humano.
purpose: []
