layout_spectrum: 0.8843850551050452
typography_spectrum: 0.48070087060489053
color:
  brandStrength: 0.8327605133490765
  lightness: 0.15706513537702582
  saturation: 0.1461460644039003
  rhythmicContrast: 0.9971759303284827
  brandColors:
    - '#FFFFFF'
    - '#31BBAC'
    - '#D73226'
    - '#414242'
    - '#A6A8AB'
content_rating:
  adult: false
github: true
analytics:
  twitter: ''
  google: UA-93195675-1
  facebook: '381066988943490'
author:
  name: Henrique Utsch
  email: henriqueutsch@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0c7a00db-db0b-4da9-81fd-b20320e6fdf2.png
name: FullLifeAcademy
url: 'http://www.fulllifeacademy.com.br/'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: Facebook
    url: 'https://www.facebook.com/FullLifeAcademyCourse/'
    type: external
  - name: YouTube
    url: 'https://www.youtube.com/channel/UC9SaqyNSlScKfchf8FEH4SA'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/99ee198f-247b-45a6-8fb5-020262d87978.png
title: Full Life Academy
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/efae450d-c759-4bdb-8774-8a1eeaa8cbf6.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/efae450d-c759-4bdb-8774-8a1eeaa8cbf6.png
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: >-
  A proposta é reunir ferramentas para impulsionar o ser humano a outro patamar.
  Muito mais elevado e completo. Reunindo as áreas mais procuradas com o
  propósito de uma vida mais feliz e plena onde todos os cursos se conectam
  preparando o ser humano para a nova era da humanidade. Uma era com humanos
  mais conscientes e bem preparados para uma vida com propósito, tecnologia e
  espiritualidade. Desenvolva todas as suas capacidades como ser humano.
purpose: []
